In [3]:
import pandas as pd
import numpy as np

## 2. How to create a series from a list, numpy array and dict?

Difficulty Level: L1

Create a pandas series from each of the items below: a list, numpy and a dictionary

In [194]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [195]:
a  = pd.Series(mylist,name='alpha')
b  = pd.Series(myarr)
c  = pd.Series(mydict)

## 3. How to convert the index of a series into a column of a dataframe?
Difficulty Level: L1

Convert the series ser into a dataframe with its index as another column on the dataframe.

In [197]:
df = pd.DataFrame(c).reset_index()
df

index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

## 4. How to combine many series to form a dataframe?
Difficulty Level: L1

Combine ser1 and ser2 to form a dataframe.

In [46]:
d = pd.concat([a,b],axis=1)
d

0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25

## 5. How to assign name to the series’ index?
Difficulty Level: L1

Give a name to the series ser calling it ‘alphabets’.

In [48]:
a.name

'alpha'

## 6. How to get the items of series A not present in series B?
Difficulty Level: L2

From ser1 remove items present in ser2.



In [49]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [57]:
a= ser1[~ser1.isin(ser2)]
b= ser2[~ser2.isin(ser1)]
pd.concat([a,b])

0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64

## 8. How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?
Difficuty Level: L2

Compute the minimum, 25th percentile, median, 75th, and maximum of ser.

In [67]:
ser = pd.Series(np.random.normal(10, 5, 25))
ser.describe()

count    25.000000
mean      9.521009
std       6.056387
min      -5.605543
25%       7.684415
50%       9.046275
75%      11.909123
max      21.025932
dtype: float64

In [80]:
a=np.array(ser.describe()).round(2)
#a.iloc[3:,:]
a

array([25.  ,  9.52,  6.06, -5.61,  7.68,  9.05, 11.91, 21.03])

In [83]:
a[3:]

array([-5.61,  7.68,  9.05, 11.91, 21.03])

## 9. How to get frequency counts of unique items of a series?
Difficulty Level: L1

Calculte the frequency counts of each unique value ser.

In [85]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser

0     h
1     a
2     h
3     f
4     g
5     e
6     b
7     g
8     f
9     a
10    h
11    f
12    d
13    h
14    b
15    g
16    g
17    h
18    g
19    c
20    a
21    b
22    a
23    b
24    e
25    d
26    a
27    g
28    c
29    c
dtype: object

In [92]:
b=ser.value_counts()
b

other    14
g         6
a         5
h         5
dtype: int64

## 10. How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?
Difficulty Level: L2

From ser, keep the top 2 most frequent items as it is and replace everything else as ‘Other’.

In [90]:
ser[ser.isin(b[b<5].index)]='other'
ser

0         h
1         a
2         h
3     other
4         g
5     other
6     other
7         g
8     other
9         a
10        h
11    other
12    other
13        h
14    other
15        g
16        g
17        h
18        g
19    other
20        a
21    other
22        a
23    other
24    other
25    other
26        a
27        g
28    other
29    other
dtype: object

## 12. How to convert a numpy array to a dataframe of given shape? (L1)
Difficulty Level: L1

Reshape the series ser into a dataframe with 7 rows and 5 columns

In [94]:
ser = pd.Series(np.random.randint(1, 10, 35))

In [95]:
a = np.array(ser).reshape(7,5)
a

array([[8, 8, 3, 3, 8],
       [7, 1, 7, 4, 9],
       [3, 3, 9, 7, 3],
       [4, 5, 2, 7, 4],
       [6, 7, 4, 8, 1],
       [1, 1, 2, 3, 5],
       [7, 3, 9, 2, 3]])

In [96]:
pd.DataFrame(a)

0  1  2  3  4
0  8  8  3  3  8
1  7  1  7  4  9
2  3  3  9  7  3
3  4  5  2  7  4
4  6  7  4  8  1
5  1  1  2  3  5
6  7  3  9  2  3

## 13. How to find the positions of numbers that are multiples of 3 from a series?
Difficulty Level: L2

Find the positions of numbers that are multiples of 3 from ser.

In [110]:
ser = pd.Series(np.random.randint(1, 10, 7))
ser

0    4
1    9
2    2
3    6
4    2
5    2
6    6
dtype: int64

In [105]:
ser[(ser%3)==0].index

Int64Index([3, 4, 6], dtype='int64')

In [113]:
ser

0    4
1    9
2    2
3    6
4    2
5    2
6    6
dtype: int64

## 14. How to extract items at given positions from a series
Difficulty Level: L1

From ser, extract the items at positions in list pos.

In [115]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

In [118]:
ser.iloc[[0, 4, 8, 14, 20]]

0     a
4     e
8     i
14    o
20    u
dtype: object

In [119]:
ser.take([0, 4, 8, 14, 20])

0     a
4     e
8     i
14    o
20    u
dtype: object

## 15. How to stack two series vertically and horizontally ?
Difficulty Level: L1

Stack ser1 and ser2 vertically and horizontally (to form a dataframe).

In [120]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

In [121]:
pd.concat([ser1,ser2],axis=0)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

## 16. How to get the positions of items of series A in another series B?
Difficulty Level: L2

Get the positions of items of ser2 in ser1 as a list.

In [138]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
ser1[ser1>3].index

Int64Index([0, 1, 2, 3, 6, 7, 8], dtype='int64')

In [123]:
ser1[ser1.isin(ser2)].index # sem respeitar a posição do ser2

Int64Index([0, 4, 5, 8], dtype='int64')

In [142]:
[ser1[ser1==val].index[0] for val in ser2.values] # substituindo o indice nas mesmas posicões de ser2

[5, 4, 0, 8]

In [144]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

In [146]:
media_erro_quadratico =np.mean((truth-pred)**2)
media_erro_quadratico

0.40284176521813786

## 18. How to convert the first character of each element in a series to uppercase?
Difficulty Level: L2

Change the first character of each word to upper case in each word of ser.

In [150]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [149]:
[x.title() for x in ser] # como array 1D

['How', 'To', 'Kick', 'Ass?']

In [153]:
b=ser.map(lambda x: x.title()) # mantendo a estrutura inicial - serie

In [154]:
b

0     How
1      To
2    Kick
3    Ass?
dtype: object

## 19. How to calculate the number of characters in each word in a series?
Difficulty Level: L2

In [159]:
 c = ser.map(lambda x: len(x))
 c

0    3
1    2
2    4
3    4
dtype: int64

## 20. How to compute difference of differences between consequtive numbers of a series?
Difficulty Level: L1

Difference of differences between the consequtive numbers of ser.

In [170]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
ser.iloc[0]

1

In [172]:
a =[]
for i in range(0,len(ser)-1):
    a.append(ser.iloc[i+1] - ser.iloc[i])
a

[2, 3, 4, 5, 6, 6, 8]

In [173]:
ser.diff()

0    NaN
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    6.0
7    8.0
dtype: float64

## 21. How to convert a series of date-strings to a timeseries?
Difficiulty Level: L2

In [180]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [181]:
from dateutil.parser import parse
ser.map(lambda x: parse(x))

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

## 22. How to get the day of month, week number, day of year and day of week from a series of date strings?
Difficiulty Level: L2

Get the day of month, week number, day of year and day of week from ser.

In [213]:
from datetime import date

In [216]:
b=pd.to_datetime(ser)

In [217]:
b.dt.weekday

0    4
1    1
2    3
dtype: int64

In [209]:
w = ['dom','seg','ter','qua','qui','sex','sab']
[w[x.weekday()] for x in b]

['qui', 'ter', 'sex', 'qua', 'dom', 'sex']

## 23. How to convert year-month string to dates corresponding to the 4th day of the month?
Difficiulty Level: L2

Change ser to dates that start with 4th of the respective months.

In [212]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

In [227]:
b=ser.map(lambda x: x + ' 04')
b.map(lambda x: x.replace(' ','-'))

0    Jan-2010-04
1    Feb-2011-04
2    Mar-2012-04
dtype: object

## 24. How to filter words that contain atleast 2 vowels from a series?
Difficiulty Level: L3

From ser, extract words that contain atleast 2 vowels.

In [248]:
import re
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

In [253]:
[x for x in ser if (len(re.findall('[aeiou]',x.lower())) >=2)]

['Apple', 'Orange', 'Money']

In [252]:
[re.findall('[aeiouAeiou]',x) for x in ser]

[['A', 'e'], ['a', 'e'], ['a'], ['o'], ['o', 'e']]

## 25. How to filter valid emails from a series?
Difficiulty Level: L3

Extract the valid emails from the series emails. The regex pattern for valid emails is provided as reference.

In [259]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com','rameses'])

In [262]:
emails[emails.str.match('[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}')]# problema com @

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object

In [202]:
import re
[x for x in emails if re.match('[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}',x)]

['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']

## 26. How to get the mean of a series grouped by another series?
Difficiulty Level: L2

Compute the mean of weights of each fruit.

In [289]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
teste = pd.Series(np.random.randint(3,15,10))

In [290]:
b = pd.concat([fruit,weights,teste],axis=1)
b.columns = ['fruit','w','teste']

In [291]:
b

fruit     w  teste
0  carrot   1.0     11
1  banana   2.0      7
2  carrot   3.0      3
3  banana   4.0      7
4  banana   5.0     10
5  carrot   6.0      3
6  carrot   7.0     10
7  banana   8.0      5
8  carrot   9.0      6
9   apple  10.0      3

In [293]:
c = b.groupby('fruit')[['w','teste']]
c.mean()

w  teste
fruit               
apple   10.00   3.00
banana   4.75   7.25
carrot   5.20   6.60

In [ ]:
[b[b==x]].iloc[:1].mean() for x in]

In [ ]:
from platform import python_version
print(python_version())

## 27. How to compute the euclidean distance between two series?
Difficiulty Level: L2

Compute the euclidean distance between series (points) p and q, without using a packaged formula.

In [294]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [296]:
c = (p**2 + q**2)**(1/2)
c

0    10.049876
1     9.219544
2     8.544004
3     8.062258
4     7.810250
5     7.810250
6     8.062258
7     8.544004
8     9.219544
9    10.049876
dtype: float64

In [300]:
from platform import python_version
print(python_version())

3.8.3


In [304]:
a = p -q
b = (a@a)**0.5 # funciona para vetores, quanto temos matriz devemos considerar apenas diag(a@a)
b

18.16590212458495

## 28. How to find all the local maxima (or peaks) in a numeric series?
Difficiulty Level: L3

Get the positions of peaks (values surrounded by smaller values on both sides) in ser.

In [308]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
b=np.array(ser)

In [312]:
[i for i in range(1,len(b)-1) if ((b[i-1]<b[i]) & (b[i+1]<b[i]))]

[1, 5, 7]

## 29. How to replace missing spaces in a string with the least frequent character?
Replace the spaces in my_str with the least frequent character.

Difficiulty Level: L2

In [320]:
import re

In [386]:

my_str = 'dbc deb abed gade'
b = re.findall('[a-z]',my_str)
b

['d', 'b', 'c', 'd', 'e', 'b', 'a', 'b', 'e', 'd', 'g', 'a', 'd', 'e']

In [391]:
c = list(set(b))
soma=''
for i in range(len(c)):
    soma += c[i]
soma

'dbgeac'

In [345]:
c = pd.Series(b)

In [360]:
d = pd.Series(c.value_counts())
e = pd.DataFrame(d).reset_index()
e.columns=['a','b']
e

a  b
0  d  4
1  e  3
2  b  3
3  a  2
4  g  1
5  c  1

In [368]:
e.sort_values(by=['b','a'],ascending=True,inplace=True)

In [369]:
e.iloc[0,0]

'c'

In [393]:
my_str.replace(' ', e.iloc[0,0])

'dbccdebcabedcgade'

## 30. How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?
Difficiulty Level: L2

In [402]:
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

2000-01-01    5
2000-01-08    6
2000-01-15    3
2000-01-22    3
2000-01-29    8
2000-02-05    3
2000-02-12    4
2000-02-19    4
2000-02-26    8
2000-03-04    2
Freq: W-SAT, dtype: int64

## 31. How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?
Difficiulty Level: L2

ser has missing dates and values. Make all missing dates appear and fill up with value from previous date.

In [263]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
ser

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64

In [265]:
ser.resample('D').ffill()  # resample + fill só funciona quando datas são index

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

## 32. How to compute the autocorrelations of a numeric series?
Difficiulty Level: L3

Compute autocorrelations for the first 10 lags of ser. Find out which lag has the largest correlation.

In [440]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
ser

0      9.474798
1      3.683782
2     21.158580
3     14.375224
4     10.950101
5     -0.407993
6      7.396344
7     11.114983
8      4.671467
9      2.679203
10    33.038984
11    19.921738
12    16.111124
13     6.192056
14   -12.254243
15    21.446147
16    19.961171
17    19.811822
18    27.056672
19    28.899995
dtype: float64

In [450]:
ser.autocorr()

0.2289734399152963

In [453]:
ser.autocorr(6) # fazer loop com numero de linhas para verificar autocorr com lags de 0 a len(ser)

0.07017749510183899

## 34. How to change column values when importing csv to a dataframe?
Difficulty Level: L2

Import the boston housing dataset, but while importing change the 'medv' (median house value) column so that values < 25 becomes ‘Low’ and > 25 becomes ‘High’.

In [459]:
a = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')

In [457]:
a.head(50)

crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
0   0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296   
1   0.02731   0.0   7.07     0  0.469  6.421   78.9  4.9671    2  242   
2   0.02729   0.0   7.07     0  0.469  7.185   61.1  4.9671    2  242   
3   0.03237   0.0   2.18     0  0.458  6.998   45.8  6.0622    3  222   
4   0.06905   0.0   2.18     0  0.458  7.147   54.2  6.0622    3  222   
5   0.02985   0.0   2.18     0  0.458  6.430   58.7  6.0622    3  222   
6   0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5  311   
7   0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5  311   
8   0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5  311   
9   0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5  311   
10  0.22489  12.5   7.87     0  0.524  6.377   94.3  6.3467    5  311   
11  0.11747  12.5   7.87     0  0.524  6.009   82.9  6.2267    5  311   
12  0.09378  12.5   7.87     0  0.524  5.889   39.0  5.4509    5  311   
13  0.62976   0.0   8.14     0  0.538  5.949   61.8  4.7075    4  307   
14  0.63796   0.0   8.14     0  0.538  6.096   84.5  4.4619    4  307   
15  0.62739   0.0   8.14     0  0.538  5.834   56.5  4.4986    4  307   
16  1.05393   0.0   8.14     0  0.538  5.935   29.3  4.4986    4  307   
17  0.78420   0.0   8.14     0  0.538  5.990   81.7  4.2579    4  307   
18  0.80271   0.0   8.14     0  0.538  5.456   36.6  3.7965    4  307   
19  0.72580   0.0   8.14     0  0.538  5.727   69.5  3.7965    4  307   
20  1.25179   0.0   8.14     0  0.538  5.570   98.1  3.7979    4  307   
21  0.85204   0.0   8.14     0  0.538  5.965   89.2  4.0123    4  307   
22  1.23247   0.0   8.14     0  0.538  6.142   91.7  3.9769    4  307   
23  0.98843   0.0   8.14     0  0.538  5.813  100.0  4.0952    4  307   
24  0.75026   0.0   8.14     0  0.538  5.924   94.1  4.3996    4  307   
25  0.84054   0.0   8.14     0  0.538  5.599   85.7  4.4546    4  307   
26  0.67191   0.0   8.14     0  0.538  5.813   90.3  4.6820    4  307   
27  0.95577   0.0   8.14     0  0.538  6.047   88.8  4.4534    4  307   
28  0.77299   0.0   8.14     0  0.538  6.495   94.4  4.4547    4  307   
29  1.00245   0.0   8.14     0  0.538  6.674   87.3  4.2390    4  307   
30  1.13081   0.0   8.14     0  0.538  5.713   94.1  4.2330    4  307   
31  1.35472   0.0   8.14     0  0.538  6.072  100.0  4.1750    4  307   
32  1.38799   0.0   8.14     0  0.538  5.950   82.0  3.9900    4  307   
33  1.15172   0.0   8.14     0  0.538  5.701   95.0  3.7872    4  307   
34  1.61282   0.0   8.14     0  0.538  6.096   96.9  3.7598    4  307   
35  0.06417   0.0   5.96     0  0.499  5.933   68.2  3.3603    5  279   
36  0.09744   0.0   5.96     0  0.499  5.841   61.4  3.3779    5  279   
37  0.08014   0.0   5.96     0  0.499  5.850   41.5  3.9342    5  279   
38  0.17505   0.0   5.96     0  0.499  5.966   30.2  3.8473    5  279   
39  0.02763  75.0   2.95     0  0.428  6.595   21.8  5.4011    3  252   
40  0.03359  75.0   2.95     0  0.428  7.024   15.8  5.4011    3  252   
41  0.12744   0.0   6.91     0  0.448  6.770    2.9  5.7209    3  233   
42  0.14150   0.0   6.91     0  0.448  6.169    6.6  5.7209    3  233   
43  0.15936   0.0   6.91     0  0.448  6.211    6.5  5.7209    3  233   
44  0.12269   0.0   6.91     0  0.448  6.069   40.0  5.7209    3  233   
45  0.17142   0.0   6.91     0  0.448  5.682   33.8  5.1004    3  233   
46  0.18836   0.0   6.91     0  0.448  5.786   33.3  5.1004    3  233   
47  0.22927   0.0   6.91     0  0.448  6.030   85.5  5.6894    3  233   
48  0.25387   0.0   6.91     0  0.448  5.399   95.3  5.8700    3  233   
49  0.21977   0.0   6.91     0  0.448  5.602   62.0  6.0877    3  233   

    ptratio       b  lstat  medv  
0      15.3  396.90   4.98  24.0  
1      17.8  396.90   9.14  21.6  
2      17.8  392.83   4.03  34.7  
3      18.7  394.63   2.94  33.4  
4      18.7  396.90   5.33  36.2  
5      18.7  394.12   5.21  28.7  
6      15.2  395.60  12.43  22.9  
7  

In [474]:
a['medv']=a['medv'].apply(lambda x: 'low' if x<25 else 'high')
a.head(5)

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98   low  
1  396.90   9.14   low  
2  392.83   4.03  high  
3  394.63   2.94  high  
4  396.90   5.33  high

In [475]:
a['nox']=a['medv'].apply(lambda x: 'a' if x=='low' else 'b')
a.head(5)

crim    zn  indus  chas nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0   a  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0   a  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0   b  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0   b  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0   b  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98   low  
1  396.90   9.14   low  
2  392.83   4.03  high  
3  394.63   2.94  high  
4  396.90   5.33  high

## 35. How to create a dataframe with rows as strides from a given series?
Difficiulty Level: L3

In [267]:
L = pd.Series(range(15))
L

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
dtype: int64

In [266]:
a= list(L[L%2==0])
b=np.zeros((1,4))

b[0:] = [i for i in range(0,4)]
for x in a[1:]:
    if b[-1,-4] == a[-3] : break      
    b=np.append(b,[[i for i in range(x,(x+4))]],axis=0)   
b

array([[ 0.,  1.,  2.,  3.],
       [ 2.,  3.,  4.,  5.],
       [ 4.,  5.,  6.,  7.],
       [ 6.,  7.,  8.,  9.],
       [ 8.,  9., 10., 11.],
       [10., 11., 12., 13.]])

## 37. How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? Also get the array and list equivalent.
Difficulty Level: L2

Get the number of rows, columns, datatype and summary statistics of each column of the Cars93 dataset. Also get the numpy array and list equivalent of the dataframe.

In [555]:
teste = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [556]:
teste.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Manufacturer        89 non-null     object 
 1   Model               92 non-null     object 
 2   Type                90 non-null     object 
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             87 non-null     object 
 9   DriveTrain          86 non-null     object 
 10  Cylinders           88 non-null     object 
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 non-null     object 
 16  Fuel.tank.

In [557]:
teste.describe()


Min.Price      Price  Max.Price   MPG.city  MPG.highway  EngineSize  \
count  86.000000  91.000000  88.000000  84.000000    91.000000   91.000000   
mean   17.118605  19.616484  21.459091  22.404762    29.065934    2.658242   
std     8.828290   9.724280  10.696563   5.841520     5.370293    1.045845   
min     6.700000   7.400000   7.900000  15.000000    20.000000    1.000000   
25%    10.825000  12.350000  14.575000  18.000000    26.000000    1.800000   
50%    14.600000  17.700000  19.150000  21.000000    28.000000    2.300000   
75%    20.250000  23.500000  24.825000  25.000000    31.000000    3.250000   
max    45.400000  61.900000  80.000000  46.000000    50.000000    5.700000   

       Horsepower          RPM  Rev.per.mile  Fuel.tank.capacity  Passengers  \
count   86.000000    90.000000     87.000000           85.000000   91.000000   
mean   144.000000  5276.666667   2355.000000           16.683529    5.076923   
std     53.455204   605.554811    486.916616            3.375748    1.045953   
min     55.000000  3800.000000   1320.000000            9.200000    2.000000   
25%    100.750000  4800.000000   2017.500000           14.500000    4.000000   
50%    140.000000  5200.000000   2360.000000           16.500000    5.000000   
75%    170.000000  5787.500000   2565.000000           19.000000    6.000000   
max    300.000000  6500.000000   3755.000000           27.000000    8.000000   

           Length   Wheelbase      Width  Turn.circle  Rear.seat.room  \
count   89.000000   92.000000  87.000000    88.000000       89.000000   
mean   182.865169  103.956522  69.448276    38.954545       27.853933   
std     14.792651    6.856317   3.778023     3.304157        3.018129   
min    141.000000   90.000000  60.000000    32.000000       19.000000   
25%    174.000000   98.000000  67.000000    36.000000       26.000000   
50%    181.000000  103.000000  69.000000    39.000000       27.500000   
75%    192.000000  110.000000  72.000000    42.000000       30.000000   
max    219.000000  119.000000  78.000000    45.000000       36.000000   

       Luggage.room       Weight  
count     74.000000    86.000000  
mean      13.986486  3104.593023  
std        3.120824   600.129993  
min        6.000000  1695.000000  
25%       12.000000  2647.500000  
50%       14.000000  3085.000000  
75%       16.000000  3567.500000  
max       22.000000  4105.000000

## 38. How to extract the row and column number of a particular cell with given criterion?
Difficulty Level: L1

Input

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
Which manufacturer, model and type has the highest Price? What is the row and column number of the cell with the highest Price value?

In [588]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.head(5)

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [589]:
np.argmax(df['Price'])

58

In [591]:
df.iloc[58,:]

Manufacturer               Mercedes-Benz
Model                               300E
Type                             Midsize
Min.Price                           43.8
Price                               61.9
Max.Price                             80
MPG.city                              19
MPG.highway                           25
AirBags               Driver & Passenger
DriveTrain                          Rear
Cylinders                              6
EngineSize                           3.2
Horsepower                           217
RPM                                 5500
Rev.per.mile                        2220
Man.trans.avail                       No
Fuel.tank.capacity                  18.5
Passengers                             5
Length                               NaN
Wheelbase                            110
Width                                 69
Turn.circle                           37
Rear.seat.room                       NaN
Luggage.room                          15
Weight          

In [570]:
df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
     index=[7, 8, 9], columns=['max_speed', 'shield'])
df

max_speed  shield
7          1       2
8          4       5
9          7       8

In [576]:
df.loc[df['max_speed'] > 6, ['max_speed']] =10
df

max_speed  shield
7          1       2
8          4       5
9         10       8

In [577]:
df[df['shield']==5]=20
df

max_speed  shield
7          1       2
8         20      20
9         10       8

## 39. How to rename a specific columns in a dataframe?
Difficulty Level: L2

Rename the column Type as CarType in df and replace the ‘.’ in column names with ‘_’.

In [592]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.head(5)

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [625]:
a = pd.Series(df.columns)

In [627]:
a.replace('\.','_',inplace=True,regex=True)
df.columns = a

In [628]:
df.head(3)

Manufacturer    Model     Type  Min_Price  Price  Max_Price  MPG_city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   

   MPG_highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   

   Wheelbase  Width  Turn_circle Rear_seat_room  Luggage_room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  

[3 rows x 27 columns]

## 41. How to count the number of missing values in each column?
Difficulty Level: L2

Count the number of missing values in each column of df. Which column has the maximum number of missing values?

In [657]:
b = pd.Series([1,np.nan,3,4,np.nan,9,7])
b

0    1.0
1    NaN
2    3.0
3    4.0
4    NaN
5    9.0
6    7.0
dtype: float64

In [658]:
b.isnull().sum()

2

In [661]:

a=[df[x].isnull().sum() for x in list(df.columns)]
b=pd.Series(a,index=list(df.columns))
b

Manufacturer           4
Model                  1
Type                   3
Min_Price              7
Price                  2
Max_Price              5
MPG_city               9
MPG_highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev_per_mile           6
Man_trans_avail        5
Fuel_tank_capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn_circle            5
Rear_seat_room         4
Luggage_room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

## 42. How to replace missing values of multiple numeric columns with the mean?
Difficulty Level: L2

Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [673]:
df['Min_Price'].fillna(df['Min_Price'].mean(),inplace=True)
df['Max_Price'].fillna(df['Max_Price'].mean(),inplace=True)

In [671]:
df.head()

Manufacturer    Model     Type  Min_Price  Price  Max_Price  MPG_city  \
0        Acura  Integra    Small  12.900000   15.9       18.8      25.0   
1          NaN   Legend  Midsize  29.200000   33.9       38.7      18.0   
2         Audi       90  Compact  25.900000   29.1       32.3      20.0   
3         Audi      100  Midsize  17.118605   37.7       44.6      19.0   
4          BMW     535i  Midsize  17.118605   30.0        NaN      22.0   

   MPG_highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn_circle Rear_seat_room  Luggage_room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

## 44. How to select a specific column from a dataframe as a dataframe instead of a series?
Difficulty Level: L2

Get the first column (a) in df as a dataframe (rather than as a Series).

In [675]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [676]:
b = df[['a']]
b

a
0   0
1   5
2  10
3  15

In [677]:
type(b)

pandas.core.frame.DataFrame

## 45. How to change the order of columns of a dataframe?
Difficulty Level: L3

Actually 3 questions.

In df, interchange columns 'a' and 'c'.
Create a generic function to interchange two columns, without hardcoding column names.

Sort the columns in reverse alphabetical order, that is colume 'e' first through column 'a' last.

In [698]:
df = df[['c','b','a','d','e']]
df

c   b   a   d   e
0   2   0   1   3   4
1   7   5   6   8   9
2  12  10  11  13  14
3  17  15  16  18  19

In [701]:
def inter(x,y,df):
    lis=list(df.columns)
    index_x=lis.index(x)
    index_y=lis.index(y)
    lis[index_x]=y
    lis[index_y]=x
    df=df[lis]
    return df

a=inter('a','b',df)
a

c   a   b   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

In [708]:
lis=list(df.columns)
lis.sort(reverse=True)
df=df[lis]
df

e   d   c   b   a
0   4   3   2   0   1
1   9   8   7   5   6
2  14  13  12  10  11
3  19  18  17  15  16

## 48. How to format all the values in a dataframe as percentages?
Difficulty Level: L2

Format the values in column 'random' of df as percentages.

In [710]:
df = pd.DataFrame(np.random.random(4), columns=['random'])

out = df.style.format({
    'random': '{0:.2%}'.format,
})

out

In [270]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [275]:
df.iloc[::20,:][['Manufacturer', 'Model', 'Type']]# quando fetures não sequenciais
df.iloc[::20,0:2]# quando sequencial
df.loc[::20,['Manufacturer', 'Model', 'Type']]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

## 50. How to create a primary key index by combining relevant columns?
Difficulty Level: L2

In df, Replace NaNs with ‘missing’ in columns 'Manufacturer', 'Model' and 'Type' and create a index as a combination of these three columns and check if the index is a primary key.

In [765]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

missing = {'Manufacturer': 'missing', 'Model': 'missing', 'Type': 'missing'}
aux=df.fillna(value=missing)
aux.isnull().sum()
aux

Manufacturer    Model     Type  Min.Price  Max.Price
0         Acura  Integra    Small       12.9       18.8
1       missing   Legend  Midsize       29.2       38.7
2          Audi       90  Compact       25.9       32.3
3          Audi      100  Midsize        NaN       44.6
4           BMW     535i  Midsize        NaN        NaN
..          ...      ...      ...        ...        ...
88   Volkswagen  Eurovan      Van       16.6       22.7
89   Volkswagen   Passat  Compact       17.6       22.4
90   Volkswagen  Corrado   Sporty       22.9       23.7
91        Volvo      240  Compact       21.8       23.5
92      missing      850  Midsize       24.8       28.5

[93 rows x 5 columns]

In [768]:

lis = [aux.iloc[i]['Manufacturer']+aux.iloc[i]['Model']+aux.iloc[i]['Type'] for i in range(len(aux))]
df =pd.DataFrame(aux.values,index=lis,columns=aux.columns)
df


Manufacturer    Model     Type Min.Price Max.Price
AcuraIntegraSmall              Acura  Integra    Small      12.9      18.8
missingLegendMidsize         missing   Legend  Midsize      29.2      38.7
Audi90Compact                   Audi       90  Compact      25.9      32.3
Audi100Midsize                  Audi      100  Midsize       NaN      44.6
BMW535iMidsize                   BMW     535i  Midsize       NaN       NaN
...                              ...      ...      ...       ...       ...
VolkswagenEurovanVan      Volkswagen  Eurovan      Van      16.6      22.7
VolkswagenPassatCompact   Volkswagen   Passat  Compact      17.6      22.4
VolkswagenCorradoSporty   Volkswagen  Corrado   Sporty      22.9      23.7
Volvo240Compact                Volvo      240  Compact      21.8      23.5
missing850Midsize            missing      850  Midsize      24.8      28.5

[93 rows x 5 columns]

## 51. How to get the row number of the nth largest value in a column?
Difficulty Level: L2

Find the row position of the 5th largest value of column 'a' in df.

In [771]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,3), columns=list('abc'))
df

a   b   c
0   3  19   5
1  12  29   3
2   3  16   5
3   3  22   2
4   1  12  14
5   9   3  16
6   2  19  18
7   8  21  10
8  13   7   4
9  26   4  14

In [774]:
df.sort_values(by='a',inplace=True)

a   b   c
4   1  12  14
6   2  19  18
0   3  19   5
2   3  16   5
3   3  22   2
7   8  21  10
5   9   3  16
1  12  29   3
8  13   7   4
9  26   4  14

In [777]:
df.iloc[-5].name


5

## 52. How to find the position of the nth largest value greater than a given value?
Difficulty Level: L2

In ser, find the position of the 2nd largest value greater than the mean.

In [784]:
ser = pd.Series([7, 77, 16, 86, 60, 38, 34, 36, 83, 27, 16, 52, 50, 52, 54] )
a= ser.sort_values()
a

0      7
2     16
10    16
9     27
6     34
7     36
5     38
12    50
11    52
13    52
14    54
4     60
1     77
8     83
3     86
dtype: int64

In [785]:
b=a[a>a.mean()]
b

12    50
11    52
13    52
14    54
4     60
1     77
8     83
3     86
dtype: int64

## 53. How to get the last n rows of a dataframe with row sum > 100?
Difficulty Level: L2

Get the last two rows of df whose row sum is greater than 100.



In [291]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df

0   1   2   3
0   13  31  20  22
1   38  11  18  19
2   15  32  12  13
3   37  19  18  37
4   33  25  12  37
5   33  29  27  20
6   27  13  13  31
7   20  31  27  36
8   30  19  28  33
9   28  23  20  31
10  15  30  20  16
11  14  10  11  13
12  11  35  14  14
13  36  20  24  33
14  27  29  34  27

In [292]:
rowsums= df.sum(axis=1)
rowsums = df.apply(np.sum, axis=1)
rowsums


0      86
1      86
2      72
3     111
4     107
5     109
6      84
7     114
8     110
9     102
10     81
11     48
12     74
13    113
14    117
dtype: int64

In [309]:
df[rowsums>100]

0   1   2   3
3   37  19  18  37
4   33  25  12  37
5   33  29  27  20
7   20  31  27  36
8   30  19  28  33
9   28  23  20  31
13  36  20  24  33
14  27  29  34  27

In [313]:
df[rowsums>100].iloc[-2:,:]

0   1   2   3
13  36  20  24  33
14  27  29  34  27

## 54. How to find and cap outliers from a series or dataframe column?
Difficulty Level: L2

Replace all values of ser in the lower 5%ile and greater than 95%ile with respective 5th and 95th %ile value.

In [315]:
ser = pd.Series(np.logspace(-2, 2, 30))

In [316]:
low, high =ser.quantile([.5,.95])

In [326]:
#ser[ser<low]=low
#ser[ser>high]=high
# eliminando outlines

ser[(ser>low) & (ser<high)]

15     1.172102
16     1.610262
17     2.212216
18     3.039195
19     4.175319
20     5.736153
21     7.880463
22    10.826367
23    14.873521
24    20.433597
25    28.072162
26    38.566204
27    52.983169
dtype: float64

## 55. How to reshape a dataframe to the largest possible square after removing the negative values?
Difficulty Level: L3

Reshape df to the largest possible square with negative values removed. Drop the smallest values if need be. The order of the positive numbers in the result should remain the same as the original.

In [284]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
df

0   1   2   3   4   5   6   7   8   9
0  25  36   9 -13   8  41  20  46  41  36
1   3  33   3  39   1  -7   7  -9  -9 -11
2  40  47 -16 -11 -16  20 -12  -1  35 -15
3  36  39  34  -8  38 -18  -1 -15  31  20
4   3  44 -10  41  39  11  -6  39  20 -14
5  -2  30  33  -1  15  46 -20  47 -18  44
6 -15  49   6  42   3   1 -12 -12  47  -2
7  23 -16  27  40  35   1 -18  22  -5  19
8  -2  26  28 -14  -5  18  -1  39  -6 -19
9  -3  49  40  10 -16  47 -12  39 -11  45

In [823]:
a = np.array(df)
a=a.reshape(100)
a=a[a>0]
a.shape[0]
b=np.argsort(a)
a

array([43, 26, 17, 17, 15, 36, 23, 37, 33,  7, 41, 44, 27,  7, 26, 13, 41,
       19, 11, 17, 32, 37,  9, 11,  8, 22, 35, 29, 30, 14,  5, 40, 21, 25,
       26, 43, 46, 40,  3, 14, 40, 33, 36, 37, 14, 21, 13, 28, 36,  9, 28,
       27, 33, 10,  5, 26, 25, 47, 47, 11, 13, 48, 15, 23,  4, 29, 15, 19])

In [825]:
b[:4]

array([38, 64, 54, 30])

In [827]:
a=np.delete(a,b[:4])

In [833]:
dimp2 = int((a.shape[0])**(0.5))

In [835]:
a=a.reshape(dimp2,dimp2)
a

array([[43, 26, 17, 17, 15, 36, 23, 37],
       [33,  7, 41, 44, 27,  7, 26, 13],
       [41, 19, 11, 17, 32, 37,  9, 11],
       [ 8, 22, 35, 29, 30, 14, 40, 21],
       [25, 26, 43, 46, 40, 14, 40, 33],
       [36, 37, 14, 21, 13, 28, 36,  9],
       [28, 27, 33, 10, 26, 25, 47, 47],
       [11, 13, 48, 15, 23, 29, 15, 19]])

## 56. How to swap two rows of a dataframe?
Difficulty Level: L2

Swap rows 1 and 2 in df.

In [837]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df

    

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [847]:
def invert(x,y,df):
    aux = df.copy()
    val_x = df.iloc[x].name
    val_y= df.iloc[y].name
    aux.iloc[x] =df.iloc[val_y]
    aux.iloc[y] =df.iloc[val_x]
    return aux

df = invert(2,3,df)
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  15  16  17  18  19
3  10  11  12  13  14
4  20  21  22  23  24

## 57. How to reverse the rows of a dataframe?
Difficulty Level: L2

Reverse all the rows of dataframe df.

In [849]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [852]:
aux = df.copy()
aux=aux.sort_index(ascending=False)
aux

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

## 59. Which column contains the highest number of row-wise maximum values?
Difficulty Level: L2

Obtain the column name with the highest number of row-wise maximum’s in df.

In [859]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
a=[df[x].sum() for x in df.columns]
np.argmax(a)

3

## 60. How to create a new column that contains the row number of nearest column by euclidean distance?
Create a new column such that, each row contains the row number of nearest row-record by euclidean distance.

Difficulty Level: L3

In [884]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
aux = np.array(df)
aux.shape
#a=(aux[1:]-aux)
#aux[1,:]

(10, 4)

In [930]:
lin=[]
dist=[]
for i in range(len(aux)):
    dif_p =(aux[i,:]-aux)# distancia entre ponto da linha i x todas as linhas (10x4)
    som_prod=(dif_p@(dif_p.T))# calc soma do produto de cada linha utilizando produto de matrizes: (10x4)@(4x10)-> 10x10   
    mod= som_prod.diagonal()**(0.5) # diagonal igual ao modulo ao quadrado de cada linha 
    mod = np.delete(mod,[i]) # retirando o valor 0 que é a dinstancia de um ponto pra ele mesmo
    lin.append(np.argmin(mod))
    dist.append(mod[np.argmin(mod)])

In [931]:
df['nearest_row']= list(map(lambda x: df.index[x] ,lin))

In [932]:
df['dist']= dist

In [933]:
df

p   q   r   s nearest_row       dist
a  79  37  70  36           b  31.032241
b  77  19  97  34           a  32.572995
c  67  54  93  37           a  31.032241
d  85   9  63  13           a  37.389838
e  82  71  70  19           c  36.972963
f  10  31  54  49           i  46.722586
g  15  52  86  82           f  50.783856
h  30  86  31  49           h  52.019227
i  11  91  27   1           h  52.019227
j   3  49  93  32           f  46.722586

## 62. How to create a column containing the minimum by maximum of each row?
Difficulty Level: L2

Compute the minimum-by-maximum for every row of df.

In [934]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df

0   1   2   3   4   5   6   7   8   9
0  65  56  51  95  43  71  74  11  48  38
1  49  19  36  74  88  30   7  46  72  57
2   2  69  34  36  57  81  78  14  38  72
3  69  40  81  52  89  89  36  82  77  28
4  60   8  57  90  13  20  91   6  82  86
5  21  42  50  25  54  99  41  51  22  25
6  21  96  11  80  90  43  38  60  25  34
7  47  58  56  39  25  63  46  92  36  31

In [939]:
df['sum_por_lin']=list(df.sum(axis=1))
df

0   1   2   3   4   5   6   7   8   9  sum_por_lin
0  65  56  51  95  43  71  74  11  48  38          552
1  49  19  36  74  88  30   7  46  72  57          478
2   2  69  34  36  57  81  78  14  38  72          481
3  69  40  81  52  89  89  36  82  77  28          643
4  60   8  57  90  13  20  91   6  82  86          513
5  21  42  50  25  54  99  41  51  22  25          430
6  21  96  11  80  90  43  38  60  25  34          498
7  47  58  56  39  25  63  46  92  36  31          493

## 63. How to create a column that contains the penultimate value in each row?
Difficulty Level: L2

Create a new column 'penultimate' which has the second largest value of each row of df.

In [962]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df

0   1   2   3   4   5   6   7   8   9
0  31  55  67  52  51  18  23  29  53  25
1  73  92  37  61  41  26  28  37  64   9
2  13  23  84  95  24  75  33   8  48  30
3  31  14  41  34  26  30  82  10  95  99
4  22  11  24  73  64  13  55   9  62  70
5   4  42  95  78  60  64  42  73  61  88
6  22  87  68  27  28   1  86  55  33  88
7  34  28  75  67  96  15  42  52  28  71

In [963]:
res=[]
for i in range(len(df)):
    a=np.array(df.iloc[i,:])
    b=a[np.argsort(a)]
    res.append(b[-2])

In [964]:
df['sec_max'] = res
df

0   1   2   3   4   5   6   7   8   9  sec_max
0  31  55  67  52  51  18  23  29  53  25       55
1  73  92  37  61  41  26  28  37  64   9       73
2  13  23  84  95  24  75  33   8  48  30       84
3  31  14  41  34  26  30  82  10  95  99       95
4  22  11  24  73  64  13  55   9  62  70       70
5   4  42  95  78  60  64  42  73  61  88       88
6  22  87  68  27  28   1  86  55  33  88       87
7  34  28  75  67  96  15  42  52  28  71       75

## 64. How to normalize all columns in a dataframe?
Difficulty Level: L2

Normalize all columns of df by subtracting the column mean and divide by standard deviation.
Range all columns of df such that the minimum value in each column is 0 and max is 1.
Don’t use external packages like sklearn.

In [979]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
aux=np.array(df)
aux

array([[44, 67, 75, 43, 27, 20, 85, 81, 14, 72],
       [60,  5,  2, 92, 25, 45, 49, 37, 74, 87],
       [58,  7, 45, 41, 33, 23, 62, 21, 77, 42],
       [11, 58, 63, 48, 15, 27,  3, 79, 83, 70],
       [61, 83, 60,  8, 43, 47,  7, 84, 28, 28],
       [33, 20, 26, 77, 45, 53, 64,  9, 65, 40],
       [90, 31, 49, 25,  7, 56, 74, 91, 94, 27],
       [41,  2, 66,  3, 13, 26, 44, 13,  7, 74]])

In [981]:
media= np.mean(aux,axis=0)
media.round(2)

array([49.75, 34.12, 48.25, 42.12, 26.  , 37.12, 48.5 , 51.88, 55.25,
       55.  ])

In [983]:
desvio= np.std(aux,axis=0)
desvio.round(2)

array([21.83, 29.29, 22.45, 29.  , 13.  , 13.63, 27.88, 32.92, 31.55,
       21.81])

In [990]:
((aux-media)/desvio).round(1)

array([[-0.3,  1.1,  1.2,  0. ,  0.1, -1.3,  1.3,  0.9, -1.3,  0.8],
       [ 0.5, -1. , -2.1,  1.7, -0.1,  0.6,  0. , -0.5,  0.6,  1.5],
       [ 0.4, -0.9, -0.1, -0. ,  0.5, -1. ,  0.5, -0.9,  0.7, -0.6],
       [-1.8,  0.8,  0.7,  0.2, -0.8, -0.7, -1.6,  0.8,  0.9,  0.7],
       [ 0.5,  1.7,  0.5, -1.2,  1.3,  0.7, -1.5,  1. , -0.9, -1.2],
       [-0.8, -0.5, -1. ,  1.2,  1.5,  1.2,  0.6, -1.3,  0.3, -0.7],
       [ 1.8, -0.1,  0. , -0.6, -1.5,  1.4,  0.9,  1.2,  1.2, -1.3],
       [-0.4, -1.1,  0.8, -1.3, -1. , -0.8, -0.2, -1.2, -1.5,  0.9]])

In [991]:
teste = np.array([[1,2,3], [4,5,6], [7,8,9]])
teste

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [992]:
teste + [1,2,3]

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [993]:
teste + [[1],[2],[3]]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

## 65. How to compute the correlation of each row with the suceeding row?
Difficulty Level: L2

Compute the correlation of each row of df with its succeeding row.

In [994]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

[(df.iloc[i,:]).corr(df.iloc[i+1,:]) for i in range(len(df)-1)]

[-0.4371746454345416,
 -0.4011743482761251,
 0.10809606236144863,
 0.01846842284615097,
 -0.1956602462227333,
 0.21590301137351375,
 0.4857099582426416]

## 66. How to replace both the diagonals of dataframe with 0?
Difficulty Level: L2

Replace both values in both diagonals of df with 0.

In [1026]:
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
aux=np.array(df)
aux

array([[40, 93, 26, 36,  1, 84, 91, 46, 78,  6],
       [77, 48, 12, 22, 72, 34, 12, 78, 77, 91],
       [35, 34, 96, 17, 53, 67, 43,  1,  2,  7],
       [38, 54, 41, 73, 44,  2, 72, 44, 39, 99],
       [99, 88, 29, 71, 18, 93, 25,  6, 72, 71],
       [87, 10,  2,  9, 56,  7, 59, 71, 87, 77],
       [92, 20, 43, 31, 59, 93, 90, 57, 21, 62],
       [40, 16, 92, 42, 25, 68, 31, 11, 66, 47],
       [60, 26, 69, 74, 83, 11, 63, 84, 25, 28],
       [14, 46, 64, 44, 16, 93, 47,  6, 91, 78]])

In [1027]:
dim =np.diag_indices(10)
aux[dim]=0
aux

array([[ 0, 93, 26, 36,  1, 84, 91, 46, 78,  6],
       [77,  0, 12, 22, 72, 34, 12, 78, 77, 91],
       [35, 34,  0, 17, 53, 67, 43,  1,  2,  7],
       [38, 54, 41,  0, 44,  2, 72, 44, 39, 99],
       [99, 88, 29, 71,  0, 93, 25,  6, 72, 71],
       [87, 10,  2,  9, 56,  0, 59, 71, 87, 77],
       [92, 20, 43, 31, 59, 93,  0, 57, 21, 62],
       [40, 16, 92, 42, 25, 68, 31,  0, 66, 47],
       [60, 26, 69, 74, 83, 11, 63, 84,  0, 28],
       [14, 46, 64, 44, 16, 93, 47,  6, 91,  0]])

In [1028]:
flip_aux=np.flip(aux,axis=1)
flip_aux[dim]=0
aux = np.flip(flip_aux,axis=1)
aux

array([[ 0, 93, 26, 36,  1, 84, 91, 46, 78,  0],
       [77,  0, 12, 22, 72, 34, 12, 78,  0, 91],
       [35, 34,  0, 17, 53, 67, 43,  0,  2,  7],
       [38, 54, 41,  0, 44,  2,  0, 44, 39, 99],
       [99, 88, 29, 71,  0,  0, 25,  6, 72, 71],
       [87, 10,  2,  9,  0,  0, 59, 71, 87, 77],
       [92, 20, 43,  0, 59, 93,  0, 57, 21, 62],
       [40, 16,  0, 42, 25, 68, 31,  0, 66, 47],
       [60,  0, 69, 74, 83, 11, 63, 84,  0, 28],
       [ 0, 46, 64, 44, 16, 93, 47,  6, 91,  0]])

## 67. How to get the particular group of a groupby dataframe by key?
Difficulty Level: L2

This is a question related to understanding of grouped dataframe. From df_grouped, get the group belonging to 'apple' as a dataframe.

In [1030]:
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})
df

col1      col2  col3
0   apple  0.325843    11
1  banana  0.182801     8
2  orange  0.653354     2
3   apple  0.901559    14
4  banana  0.272996    13
5  orange  0.859957    14
6   apple  0.897826    10
7  banana  0.602927    14
8  orange  0.393504     1

In [1036]:
aux=df[df['col1']=='apple']
aux


col1      col2  col3
0  apple  0.325843    11
3  apple  0.901559    14
6  apple  0.897826    10

In [1048]:
group_aux = aux.groupby(by=['col2','col3'])
pd.DataFrame(group_aux.groups)


0.325843 0.897826 0.901559
        11       10       14
0        0        6        3

## 68. How to get the n’th largest value of a column when grouped by another column?
Difficulty Level: L2

In df, find the second largest value of 'taste' for 'banana'

In [1050]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
df

fruit     taste  price
0   apple  0.531902      2
1  banana  0.581331      6
2  orange  0.076315      4
3   apple  0.183276      4
4  banana  0.828762      2
5  orange  0.036349      7
6   apple  0.651895      2
7  banana  0.311661      8
8  orange  0.887231     14

In [1156]:
aux_groups=df.groupby(by=['fruit'])
aux_groups[['taste']].get_group('banana').sort_values(by='taste').iloc[-1]


taste
1  0.581331
4  0.828762
7  0.311661

In [1073]:
aux_groups.groups.keys()

dict_keys(['apple', 'banana', 'orange'])

In [1074]:
aux_groups.groups.values()

dict_values([Int64Index([0, 3, 6], dtype='int64'), Int64Index([1, 4, 7], dtype='int64'), Int64Index([2, 5, 8], dtype='int64')])

In [1142]:
aux_groups[['taste']].mean()

taste
fruit           
apple   0.455691
banana  0.573918
orange  0.333298

In [1109]:
lis=list(aux_groups.groups['banana']).describe()

[1, 4, 7]

In [1125]:
df

fruit     taste  price
0   apple  0.531902      2
1  banana  0.581331      6
2  orange  0.076315      4
3   apple  0.183276      4
4  banana  0.828762      2
5  orange  0.036349      7
6   apple  0.651895      2
7  banana  0.311661      8
8  orange  0.887231     14

In [1130]:
df['fruit'].index.isin(['banana'])

array([False, False, False, False, False, False, False, False, False])

In [1145]:
df.iloc[list(aux_groups.groups['banana']),:]['taste'] +1

1    1.581331
4    1.828762
7    1.311661
Name: taste, dtype: float64

## 69. How to compute grouped mean on pandas dataframe and keep the grouped column as another column (not index)?
Difficulty Level: L1

In df, Compute the mean price of every fruit, while keeping the fruit as another column instead of an index.

In [1158]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
df

fruit    rating  price
0   apple  0.754992      2
1  banana  0.693931     13
2  orange  0.594358      8
3   apple  0.914538     14
4  banana  0.745988      5
5  orange  0.757525      5
6   apple  0.128086     11
7  banana  0.289520     14
8  orange  0.817181     13

In [1162]:
df.groupby('fruit',as_index=False).mean()

fruit    rating      price
0   apple  0.599205   9.000000
1  banana  0.576480  10.666667
2  orange  0.723021   8.666667

## 70. How to join two dataframes by 2 columns so they have only the common rows?
Difficulty Level: L2

Join dataframes df1 and df2 by ‘fruit-pazham’ and ‘weight-kilo’.

In [1181]:
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})
df1

fruit    kilo
0   apple    high
1  banana  medium
2  orange     low
3   apple    high
4  banana  medium
5  orange     low
6   apple    high
7  banana  medium
8  orange     low

In [ ]:
df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

In [1169]:
pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'],suffixes=['_1', '_2'])

fruit weight  price_1  pazham  kilo  price_2
0   apple   high        5   apple  high        4
1   apple   high        8   apple  high        4
2   apple   high        2   apple  high        4
3  orange    low       14  orange   low        3
4  orange    low        1  orange   low        3
5  orange    low        9  orange   low        3

## 71. How to get the positions where values of two columns match?
Difficulty Level: L2

In [ ]:
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'kilo': ['high', 'medium', 'low'] * 3,})
df1

In [ ]:
df2 = pd.DataFrame({'fruit': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,})
df2

In [1187]:
print(df1[~df1.isin(df2).all(1)])

    fruit    kilo
1  banana  medium
2  orange     low
3   apple    high
4  banana  medium
5  orange     low
6   apple    high
7  banana  medium
8  orange     low


In [1196]:
df1[df1['fruit'].isin(df2['fruit'])].index


ValueError: Can only compare identically-labeled Series objects

In [1203]:
df1 = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

df2= pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
df2

fruit1  fruit2
0  orange  orange
1  banana  orange
2   apple  banana
3  orange  banana
4  banana  orange
5   apple  banana
6  banana  banana
7  banana  banana
8   apple  banana
9   apple  orange

In [1204]:
np.where(df1.fruit1==df2.fruit1) # funciona quando dataframes comparados possuem as mesmas features(com mesmo nome), incluindo as não comparadas

(array([0, 4, 5, 9]),)

## 72. How to create lags and leads of a column in a dataframe?
Difficulty Level: L2

Create two new columns in df, one of which is a lag1 (shift column a down by 1 row) of column ‘a’ and the other is a lead1 (shift column b up by 1 row).

In [6]:
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))
df

a   b   c   d
0  29  65  35  23
1  33  36  33  32
2  51  50  81  37
3  15   6  10  61
4  84  89  65  65

In [8]:
df['a'].shift(1,axis=0)

0    33.0
1    51.0
2    15.0
3    84.0
4     NaN
Name: a, dtype: float64

In [ ]:
df['b'].shift(-1,axis=0)

In [22]:
[x for x in df['a']]

[29, 33, 51, 15, 84]

## 73. How to get the frequency of unique values in the entire dataframe?
Difficulty Level: L2

Get the frequency of unique values in the entire dataframe df.

In [60]:
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))
df

a  b  c  d
0  2  3  3  4
1  1  9  2  2
2  5  4  9  7
3  7  1  7  2
4  8  6  1  5

In [26]:
df['a'].value_counts()

9    2
7    1
4    1
8    1
Name: a, dtype: int64

In [28]:
df.melt()['value'].value_counts()

8    4
5    3
1    3
9    2
4    2
3    2
2    2
7    1
6    1
Name: value, dtype: int64

In [30]:
df.index = ['a','b','c','d','e']

In [31]:
df

a  b  c  d
a  9  3  5  6
b  9  1  8  2
c  4  8  2  4
d  7  5  1  3
e  8  5  8  1

In [32]:
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [36]:
df['a']['c']

4

## 74. How to split a text column into two separate columns?
Difficulty Level: L2

Split the string column in df to form a dataframe with 3 columns as shown.

In [150]:
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])
df

row
0          STD, City    State
1  33, Kolkata    West Bengal
2   44, Chennai    Tamil Nadu
3  40, Hyderabad    Telengana
4  80, Bangalore    Karnataka

In [151]:
df['row']=df['row'].str.replace(r'(.*), (\w+)    (\w+)',r'\1,\2,\3',regex=True)
df

row
0          STD,City,State
1  33,Kolkata,West Bengal
2   44,Chennai,Tamil Nadu
3  40,Hyderabad,Telengana
4  80,Bangalore,Karnataka

In [159]:
a=df['row'].str.split(',',expand=True)
a

0          1            2
0  STD       City        State
1   33    Kolkata  West Bengal
2   44    Chennai   Tamil Nadu
3   40  Hyderabad    Telengana
4   80  Bangalore    Karnataka

In [160]:
X = [3, 6, 1, 9, 2, 4, 7]

In [166]:

print(X[:0:-1])


[7, 4, 2, 9, 1, 6]


In [170]:
A = [9, 2, 5, 7]
B = [x for x in range(12,21,3)]
A.append(B)
print(A)

[9, 2, 5, 7, [12, 15, 18]]


In [171]:
a=(1,2,3)

In [172]:
a[0]

1

In [174]:
estrutura_aninhada = ( [1,2,3],(4,5,6,7),[8,9],( [10,11,12], [(13, 14), 15] ) )
estrutura_aninhada[3][1][0][0]

13

In [178]:
dic = { "MG": {"Capital": "Belo Horizonte", 
               "Cidades": {1:"Contagem", 
                           2:"Luiz de Fora", 
                           3:"Sete Lagoas"}
              },
        "SP": {"Capital": "São Paulo", 
               "Cidades": {1:"Campinas", 
                           2:"Piracicaba",
                           3:"Franca"}
              },
        "RS": {"Capital": "Porto Alegre", 
               "Cidades": {1:"Pelotas", 
                           2:"Gramado", 
                           3:"Canela"}
              } 
      }

In [179]:
dic["MG"]["Cidades"][2] = "Juiz de Fora"

In [180]:
dic


{'MG': {'Capital': 'Belo Horizonte',
  'Cidades': {1: 'Contagem', 2: 'Juiz de Fora', 3: 'Sete Lagoas'}},
 'SP': {'Capital': 'São Paulo',
  'Cidades': {1: 'Campinas', 2: 'Piracicaba', 3: 'Franca'}},
 'RS': {'Capital': 'Porto Alegre',
  'Cidades': {1: 'Pelotas', 2: 'Gramado', 3: 'Canela'}}}

In [181]:
5//4

1

In [185]:
x = [i for i in range(7)]
x

[0, 1, 2, 3, 4, 5, 6]

In [186]:
def func():
    x = 1
    print(x)

x = 10
func()
print(x)

1
10


In [188]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [191]:
A = np.arange(1, 16).reshape(3,5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [193]:
print(A[A % 2 == 0])

[ 2  4  6  8 10 12 14]
